<div id="page-title">
                  <div id="theme-options" class="admin-options"> <a href="javascript:void(0);" class="btn btn-primary theme-switcher tooltip-button" data-placement="left" title="" data-original-title="Color schemes and layout options"><i class="fa fa-cog icon-spin"></i> </a>
                    <div id="theme-switcher-wrapper">
                      <div class="slimScrollDiv">
                        <div class="scroll-switcher">
                          <h5 class="header"> Header Style <a class="set-adminheader-style" data-header-bg="bg-blue" title="Remove all styles" href="javascript:void(0);">Clear</a> </h5>
                          <div class="theme-color-wrapper clearfix">
                            <h5>Solids</h5>
                            <a class="tooltip-button set-adminheader-style bg-primary" data-header-bg="bg-primary font-inverse" title="" href="javascript:void(0);" data-original-title="Primary">Primary</a> <a class="tooltip-button set-adminheader-style bg-green" data-header-bg="bg-green font-inverse" title="" href="javascript:void(0);" data-original-title="Green">Green</a> <a class="tooltip-button set-adminheader-style bg-red" data-header-bg="bg-red font-inverse" title="" href="javascript:void(0);" data-original-title="Red">Red</a> <a class="tooltip-button set-adminheader-style bg-blue" data-header-bg="bg-blue font-inverse" title="" href="javascript:void(0);" data-original-title="Blue">Blue</a> <a class="tooltip-button set-adminheader-style bg-warning" data-header-bg="bg-warning font-inverse" title="" href="javascript:void(0);" data-original-title="Warning">Warning</a> <a class="tooltip-button set-adminheader-style bg-purple" data-header-bg="bg-purple font-inverse" title="" href="javascript:void(0);" data-original-title="Purple">Purple</a> <a class="tooltip-button set-adminheader-style bg-black" data-header-bg="bg-black font-inverse" title="" href="javascript:void(0);" data-original-title="Black">Black</a>
                            <div class="clear"></div>
                            <h5 class="mrg15T">Gradients</h5>
                            <a class="tooltip-button set-adminheader-style bg-gradient-1" data-header-bg="bg-gradient-1 font-inverse" title="" href="javascript:void(0);" data-original-title="Gradient 1">Gradient 1</a> <a class="tooltip-button set-adminheader-style bg-gradient-2" data-header-bg="bg-gradient-2 font-inverse" title="" href="javascript:void(0);" data-original-title="Gradient 2">Gradient 2</a> <a class="tooltip-button set-adminheader-style bg-gradient-3" data-header-bg="bg-gradient-3 font-inverse" title="" href="javascript:void(0);" data-original-title="Gradient 3">Gradient 3</a> <a class="tooltip-button set-adminheader-style bg-gradient-4" data-header-bg="bg-gradient-4 font-inverse" title="" href="javascript:void(0);" data-original-title="Gradient 4">Gradient 4</a> <a class="tooltip-button set-adminheader-style bg-gradient-5" data-header-bg="bg-gradient-5 font-inverse" title="" href="javascript:void(0);" data-original-title="Gradient 5">Gradient 5</a> <a class="tooltip-button set-adminheader-style bg-gradient-6" data-header-bg="bg-gradient-6 font-inverse" title="" href="javascript:void(0);" data-original-title="Gradient 6">Gradient 6</a> <a class="tooltip-button set-adminheader-style bg-gradient-7" data-header-bg="bg-gradient-7 font-inverse" title="" href="javascript:void(0);" data-original-title="Gradient 7">Gradient 7</a> <a class="tooltip-button set-adminheader-style bg-gradient-8 active" data-header-bg="bg-gradient-8 font-inverse" title="" href="javascript:void(0);" data-original-title="Gradient 8">Gradient 8</a> </div>
                          <h5 class="header"> Sidebar Style <a class="set-sidebar-style" data-header-bg="" title="Remove all styles" href="javascript:void(0);">Clear</a> </h5>
                          <div class="theme-color-wrapper clearfix">
                            <h5>Solids</h5>
                            <a class="tooltip-button set-sidebar-style bg-primary" data-header-bg="bg-primary font-inverse" title="" href="javascript:void(0);" data-original-title="Primary">Primary</a> <a class="tooltip-button set-sidebar-style bg-green" data-header-bg="bg-green font-inverse" title="" href="javascript:void(0);" data-original-title="Green">Green</a> <a class="tooltip-button set-sidebar-style bg-red" data-header-bg="bg-red font-inverse" title="" href="javascript:void(0);" data-original-title="Red">Red</a> <a class="tooltip-button set-sidebar-style bg-blue" data-header-bg="bg-blue font-inverse" title="" href="javascript:void(0);" data-original-title="Blue">Blue</a> <a class="tooltip-button set-sidebar-style bg-warning" data-header-bg="bg-warning font-inverse" title="" href="javascript:void(0);" data-original-title="Warning">Warning</a> <a class="tooltip-button set-sidebar-style bg-purple" data-header-bg="bg-purple font-inverse" title="" href="javascript:void(0);" data-original-title="Purple">Purple</a> <a class="tooltip-button set-sidebar-style bg-black" data-header-bg="bg-black font-inverse" title="" href="javascript:void(0);" data-original-title="Black">Black</a>
                            <div class="clear"></div>
                            <h5 class="mrg15T">Gradients</h5>
                            <a class="tooltip-button set-sidebar-style bg-gradient-1" data-header-bg="bg-gradient-1 font-inverse" title="" href="javascript:void(0);" data-original-title="Gradient 1">Gradient 1</a> <a class="tooltip-button set-sidebar-style bg-gradient-2" data-header-bg="bg-gradient-2 font-inverse" title="" href="javascript:void(0);" data-original-title="Gradient 2">Gradient 2</a> <a class="tooltip-button set-sidebar-style bg-gradient-3" data-header-bg="bg-gradient-3 font-inverse" title="" href="javascript:void(0);" data-original-title="Gradient 3">Gradient 3</a> <a class="tooltip-button set-sidebar-style bg-gradient-4" data-header-bg="bg-gradient-4 font-inverse" title="" href="javascript:void(0);" data-original-title="Gradient 4">Gradient 4</a> <a class="tooltip-button set-sidebar-style bg-gradient-5" data-header-bg="bg-gradient-5 font-inverse" title="" href="javascript:void(0);" data-original-title="Gradient 5">Gradient 5</a> <a class="tooltip-button set-sidebar-style bg-gradient-6" data-header-bg="bg-gradient-6 font-inverse" title="" href="javascript:void(0);" data-original-title="Gradient 6">Gradient 6</a> <a class="tooltip-button set-sidebar-style bg-gradient-7" data-header-bg="bg-gradient-7 font-inverse" title="" href="javascript:void(0);" data-original-title="Gradient 7">Gradient 7</a> <a class="tooltip-button set-sidebar-style bg-gradient-8" data-header-bg="bg-gradient-8 font-inverse" title="" href="javascript:void(0);" data-original-title="Gradient 8">Gradient 8</a> </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>     